##########part5:combine the prs generated by each chr into all chrmosome


#####author:Yang Sui(ysui@broadinsititue.org)
#####Date:2025.03.15


args = commandArgs(trailingOnly=TRUE)

data <- args[1]
out <- args[2]
scr0<-read.table(data,header=F)
colnames(scr0) <- c("IID","SID","ALLELE_CT","NAMED_ALLELE_DOSAGE_SUM","effect_weight_SUM")
score <- aggregate(scr0$effect_weight_SUM, by=list(scr0[,1]), FUN=sum)
names(score)<-c("IID","effect_weight_SUM")
write.table(score,file=out,
            sep="\t",row.names=F,quote=F)


